# Generated by Django 3.2.9 on 2022-12-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('answer', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
